# Generated by Django 3.2.9 on 2021-12-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='original_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
