# Generated by Django 3.2.9 on 2021-12-06 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='deleted',
        ),
    ]
