# Generated by Django 3.2.9 on 2021-12-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='JobType',
        ),
    ]
