# Generated by Django 3.2.9 on 2021-12-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0002_auto_20211207_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.IntegerField(choices=[(1, 'Guest'), (2, 'Follower'), (3, 'Admin'), (4, 'Creator')]),
        ),
    ]
