# Generated by Django 3.2.9 on 2021-12-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0003_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.URLField(default='https://getavataaars.com/?avatarStyle=Transparent&accessoriesType=Wayfarers&hairColorCode=#714232&hairColor=SilverGray&clotheColor=Gray01&clotheColorCode=#25557C&facialHairType=BeardMagestic&clotheType=ShirtCrewNeck&eyeType=Side&eyebrowType=SadConcerned&mouthType=ScreamOpen&skinColor=Brown&topType=WinterHat2', max_length=510, null=True),
        ),
    ]
